---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/25 15:23
---
---@class Audio : BaseCpp
local Audio = class("Audio", BaseCpp)

function Audio:ctor()
    Component.ctor(self)
end

function Audio:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.Audio()
end

function Audio:Play2D(name)
    self:GetCpp():Play2D(name)
end

function Audio:Play3D(name, pos)
    self:GetCpp():Play3D(name, pos)
end

function Audio:Pause(name)
    self:GetCpp():Pause(name)
end

function Audio:Resume(name)
    self:GetCpp():Resume(name)
end

function Audio:Stop(name)
    self:GetCpp():Stop(name)
end

return Audio