---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 16:42
---
---@class Collider
local Collider = class("Collider", Component)

function Collider:ctor()
    Component.ctor(self)
end

function Collider:SetCpp()
    ---C++组件实例
    self.cpp = Cpp.Collider()
end

function Collider:GetPxShape()
    return self:GetCpp():GetPxShape()
end

function Collider:SetTrigger(isTrigger)
    self:GetCpp():SetTrigger(isTrigger)
end

function Collider:CreatePhysicMaterial()
    self:GetCpp():CreatePhysicMaterial()
end

function Collider:CreatePxShape()
    self:GetCpp():CreatePxShape()
end

function Collider:GetRigidBody()
    self:GetCpp():GetRigidBody()
end

return Collider