---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 11:07
---
---@class PhysicMaterial
---@alias float number
local PhysicMaterial = class("PhysicMaterial")

function PhysicMaterial:ctor()
    self:SetCpp()
    self.cpp:SetLuaComponent(self)
end

function PhysicMaterial:SetCpp()
    ---C++组件实例
    self.cpp = Cpp.PhysicMaterial()
end

--- GetCpp
function PhysicMaterial:GetCpp()
    return self.cpp
end

---@param dynamicFriction float
function PhysicMaterial:SetDynamicFriction(dynamicFriction)
    self:GetCpp():SetDynamicFriction(dynamicFriction)
end

---@param staticFriction float
function PhysicMaterial:SetStaticFriction(staticFriction)
    self:GetCpp():SetStaticFriction(staticFriction)
end

---@param restitution float
function PhysicMaterial:SetRestitution(restitution)
    self:GetCpp():SetRestitution(restitution)
end

---@return float
function PhysicMaterial:GetDynamicFriction()
    return self:GetCpp():GetDynamicFriction()
end

---@return float
function PhysicMaterial:GetStaticFriction()
    return self:GetCpp():GetStaticFriction()
end

---@return float
function PhysicMaterial:GetRestitution()
    return self:GetCpp():GetRestitution()
end

return PhysicMaterial