---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 11:06
---
---@class Physics
local Physics = class("Physics")

function Physics:CreatPxScene()
    return Cpp.Physics.CreatPxScene()
end

function Physics:CreatePxRigidDynamic(position, name)
    return Cpp.Physics.CreatePxRigidDynamic(position, name)
end

function Physics:CreatePxRigidStatic(position, name)
    return Cpp.Physics.CreatePxRigidStatic(position, name)
end

function Physics:CreatePxMaterial(staticFriction, dynamicFriction, restitution)
    return Cpp.Physics.CreatePxMaterial(staticFriction, dynamicFriction, restitution)
end

function Physics:CreateSphereShape(radius, pxMaterial)
    return Cpp.Physics.CreateSphereShape(radius, pxMaterial)
end

function Physics:CreateBoxShape(size, pxMaterial)
    return Cpp.Physics.CreateBoxShape(size, pxMaterial)
end

function Physics:RaycastSingle(origin, direction, distance, raycastHit)
    return Cpp.Physics.RaycastSingle(origin, direction, distance, raycastHit)
end

function Physics:GetEnableCCD()
    return Cpp.Physics.GetEnableCCD()
end

function Physics:SetEnableCCD(enable)
    Cpp.Physics.SetEnableCCD(enable)
end

return Physics