---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 11:07
---
---@class RaycastHit
local RaycastHit = class("RaycastHit", BaseCpp)

function RaycastHit:ctor()
    BaseCpp.ctor(self)
end

function RaycastHit:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.RaycastHit()
end

function RaycastHit:GetPosition()
    return self:GetCpp():GetPosition()
end

function RaycastHit:GetGameObject()
    return self:GetCpp():GetGameObject()
end

return RaycastHit