---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 11:06
---
---@class RigidBody:Component
local RigidBody = class("RigidBody", Component)

function RigidBody:ctor()
    Component.ctor(self)
end

function RigidBody:SetCpp(...)
    self.cpp = Cpp.RigidBody()
end

---@param enableCCD boolean
function RigidBody:SetEnableCCD(enableCCD)
    return self:GetCpp():SetEnableCCD(enableCCD)
end

function RigidBody:GetEnableCCD()
    self:GetCpp():GetEnableCCD()
end

---@param isDynamic boolean
function RigidBody:SetDynamic(isDynamic)
    return self:GetCpp():SetDynamic(isDynamic)
end

function RigidBody:GetDynamic()
    self:GetCpp():GetDynamic()
end

return RigidBody