---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/8 11:06
---
---@class SphereCollider
local SphereCollider = class("SphereCollider", Collider)

function SphereCollider:ctor()
    Collider.ctor(self)
end

function SphereCollider:SetCpp()
    ---C++组件实例
    self.cpp = Cpp.SphereCollider()
end

return SphereCollider