---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/18 16:26
---
---@class BaseCpp
local BaseCpp = class("BaseCpp")

function BaseCpp:ctor(...)
    self:SetCpp(...)
end

function BaseCpp:SetCpp(...)
    ---C++组件实例
    self.cpp = nil
end

--- GetCpp
function BaseCpp:GetCpp()
    return self.cpp
end

return BaseCpp
