---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/18 16:23
---
---@class Light:Component
local Light = class("Light", Component)

function Light:ctor()
    Component.ctor(self)
end

function Light:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.Light()
end

function Light:SetLightType(lightType)
    self:GetCpp():SetLightType(lightType)
end

function Light:SetColor(color)
    self:GetCpp():SetColor(color)
end

function Light:GetColor()
    return self:GetCpp():GetColor()
end

function Light:SetIntensity(intensity)
    self:GetCpp():SetIntensity(intensity)
end

function Light:GetIntensity()
    return self:GetCpp():GetIntensity()
end

function Light:SetAttenuationConst(attenuationConst)
    self:GetCpp():SetAttenuationConst(attenuationConst)
end

function Light:GetAttenuationConst()
    return self:GetCpp():GetAttenuationConst()
end

function Light:SetAttenuationLinear(attenuationLinear)
    self:GetCpp():SetAttenuationLinear(attenuationLinear)
end

function Light:GetAttenuationLinear()
    return self:GetCpp():GetAttenuationLinear()
end

function Light:SetAttenuationQuadratic(attenuationQuadratic)
    self:GetCpp():SetAttenuationQuadratic(attenuationQuadratic)
end

function Light:GetAttenuationQuadratic()
    return self:GetCpp():GetAttenuationQuadratic()
end

return Light