---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/23 17:19
---
---@class Material : BaseCpp
local Material = class("Material", BaseCpp)

function Material:ctor()
    BaseCpp.ctor(self)
end

function Material:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.Material()
end

function Material:Parse(materialPath)
    self:GetCpp():Parse(materialPath)
end

function Material:SetUniformInt(shaderPropertyName, value)
    self:GetCpp():SetUniformInt(shaderPropertyName, value)
end

function Material:SetUniformFloat(shaderPropertyName, value)
    self:GetCpp():SetUniformFloat(shaderPropertyName, value)
end

function Material:SetUniformVector3(shaderPropertyName, value)
    self:GetCpp():SetUniformVector3(shaderPropertyName, value)
end

function Material:SetTexture(shaderPropertyName, texture)
    self:GetCpp():SetTexture(shaderPropertyName, texture)
end

function Material:GetShader()
    return self:GetCpp():GetShader()
end

function Material:GetTextures()
    return self:GetCpp():GetTextures()
end

return Material