---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/23 17:19
---
---@class MeshRenderer:Component
local MeshRenderer = class("MeshRenderer", Component)

function MeshRenderer:ctor()
    Component.ctor(self)
end

function MeshRenderer:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.MeshRenderer()
end

---@param material Material
function MeshRenderer:SetMaterial(material)
    self:GetCpp():SetMaterial(material:GetCpp())
end

function MeshRenderer:GetMaterial()
    return self:GetCpp():GetMaterial()
end

---@param meshFilter MeshFilter
function MeshRenderer:SetMeshFilter(meshFilter)
    self:GetCpp():SetMeshFilter(meshFilter:GetCpp())
end

function MeshRenderer:GetMeshFilter()
    return self:GetCpp():GetMeshFilter()
end

return MeshRenderer