---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/23 17:19
---
---@class SkinnedMeshRenderer:MeshRenderer
local SkinnedMeshRenderer = class("SkinMeshRenderer", MeshRenderer)

function SkinnedMeshRenderer:ctor()
    MeshRenderer.ctor(self)
end

function SkinnedMeshRenderer:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.SkinMeshRenderer()
end

function SkinnedMeshRenderer:OnUpdate()
    self:GetCpp():OnUpdate()
end

return SkinnedMeshRenderer