---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/4/1 16:51
---
require("Function")
GameObject = require("Component/GameObject")
Component = require("Component/Component")
Transform = require("Component/Transform")

function main()
    print("Hello World!")
    local gameObject = GameObject.new("Lua-GameObject")
    print("gameObject:" .. tostring(gameObject))
    gameObject:SetName("Lua-GameObject2")
    print("gameObject name:" .. gameObject:GetName())
end