---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/23 16:58
---
---@class Animation : Component
local Animation = class("Animation", Component)

function Animation:ctor()
    Component.ctor(self)
end

function Animation:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.Animation()
end

function Animation:Play(name)
    self:GetCpp():Play(name)
end

function Animation:Stop()
    self:GetCpp():Stop()
end

function Animation:LoadFromFile(filePath, name)
    self:GetCpp():LoadFromFile(filePath, name)
end

function Animation:GetAnimationClip()
    self:GetCpp():GetAnimationClip()
end

return Animation