---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2024/5/23 16:58
---
---@class AnimationClip : BaseCpp
local AnimationClip = class("AnimationClip", BaseCpp)

function AnimationClip:ctor()
    BaseCpp.ctor(self)
end

function AnimationClip:SetCpp(...)
    ---C++组件实例
    self.cpp = Cpp.AnimationClip()
end

function AnimationClip:LoadFromFile(filePath)
    self:GetCpp():LoadFromFile(filePath)
end

function AnimationClip:GetCurrentFrameBoneMat4()
    return self:GetCpp():GetCurrentFrameBoneMat4()
end

function AnimationClip:GetCurrentFrameNormalBoneMat3()
    return self:GetCpp():GetCurrentFrameNormalBoneMat3()
end

function AnimationClip:Play()
    self:GetCpp():Play()
end

function AnimationClip:Stop()
    self:GetCpp():Stop()
end

return AnimationClip